---
resource_pool_path: "/var/lib/libvirt/pools/"
keyfile_path: "~/.ssh/id_rsa"

main_tf_path: ../../main.tf
vars_tf_path: ../../variables.tf
terraform_tfvars_path: ../../terraform.tfvars
template:
  base_path: ../../templates/terraform/
  type:
    default: default
    custom: custom
  suffix:
    main: _main.tf.tpl
    vars: _variables.tf.tpl
    tfvars: _terraform.tfvars.tpl
