---
- name: Create main.tf from template file
  template:
    src: "{{ template.base_path }}{{ template.type.custom }}{{ template.suffix.main }}"
    dest: "{{ main_tf_path }}"
  vars:
    server_list: "{{ config.servers }}"

- name: Generate default variables.tf
  template:
    src: "{{ template.base_path }}{{ template.type.custom }}{{ template.suffix.vars }}"
    dest: "{{ vars_tf_path }}"