---
- name: Create main.tf from template file
  template:
    src: ../../templates/terraform/
    dest: ../../main.tf
  vars:
    host_list: "{{ hosts }}"

- name: Generate default variables.tf
  template:
    src: "{{ template.base_path }}{{ template.type.custom }}{{ template.suffix.vars }}"
    dest: "{{ vars_tf_path }}"