---
- name: Generate default main.tf
  template:
    src: "{{ template.base_path }}{{ template.type.default }}{{ template.suffix.main }}"
    dest: "{{ main_tf_path }}"

- name: Generate default variables.tf
  template:
    src: "{{ template.base_path }}{{ template.type.default }}{{ template.suffix.vars }}"
    dest: "{{ vars_tf_path }}"

  # Generate terraform.tfvars only when file does not exist
  # to prevent overwriting user's configuration.

- name: Task name
  stat:
    path: "{{ terraform_tfvars_path }}"
  register: terraform_tfvars_file

- name: Generate terraform.tfvars
  template:
    src: "{{ template.base_path }}{{ template.type.default }}{{ template.suffix.tfvars }}"
    dest: "{{ terraform_tfvars_path }}"
  when: not terraform_tfvars_file.stat.exists