---
- name: Create main.tf from template file
  template:
    src: ../../templates/terraform/custom_main.tf.j2
    dest: ../../main.tf
  vars:
    host_list: "{{ hosts }}"

- name: Generate default variables.tf
  template:
    src: ../../templates/terraform/custom_variables.tf.j2
    dest: ../../variables.tf