---
- name: Read config file
  include_vars:
    file: "{{ config_path }}"
    name: config

- name: Generate custom main.tf file that supports deployment on multiple servers
  include_tasks: generate-custom.yml
  when: action_type == "modify"

- name: Generate main.tf file that accepts Terraform variables or yaml config files
  include_tasks: generate-default.yml
  when: action_type == "generate-tf"
