---
# Pass config path as variable
- name: Read config file
  include_vars:
    file: "{{ config_path }}"
    name: config

- name: Create main.tf from template file
  template:
    src: "{{ main_tf_template_path }}"
    dest: "{{ main_tf_path }}"
  vars:
    server_list: "{{ config.servers }}"
