- hosts: kube_control_plane[0]
  gather_facts: false
  any_errors_fatal: true
  roles: 
    - role: kubeconfig/fetch

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  roles:
    - role: kubeconfig/copy
